CREATE TABLE `neepco_procure_sih`.`org_admin` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NULL,
    `state_zone` VARCHAR(45) NULL,
    `department` VARCHAR(45) NULL,
    `email_id` VARCHAR(45) NULL,
    `password` VARCHAR(255) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
);

CREATE TABLE `neepco_procure_sih`.`vendor_info` (
    `id` INT NOT NULL AUTO_INCREMENT,    
    `cmpny_name` VARCHAR(255) NULL,
    `email` VARCHAR(100) NULL,
    `contact` VARCHAR(15) NULL,
    `address` VARCHAR(500) NULL,
    `registration_no` VARCHAR(45) NULL,
    `social_category` VARCHAR(45) NULL,
    `mse_gender` VARCHAR(45) NULL,
    `type` VARCHAR(45) NULL,
    `GSTIN` VARCHAR(45) NULL,
    `ratings` INT NULL DEFAULT 0,
    `count_prev_procure` INT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
);

CREATE TABLE `neepco_procure_sih`.`procurement_details` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `org_id` INT NULL,
    `buyer_id` INT NULL,
    `consignee_id` INT NULL,
    `pao_id` INT NULL,
    `gem_id` INT NULL,
    `vendor_id` INT NULL,
    `product` VARCHAR(255) NULL,
    `description` VARCHAR(255) NULL,
    `quantity` INT NULL DEFAULT 0,
    `unit` VARCHAR(45) NULL DEFAULT 0,
    `amount` INT NULL DEFAULT 0,
    `project` VARCHAR(45) NULL,
    `remarks` VARCHAR(255) NULL,
    `prc_status` TINYINT NULL DEFAULT 0,
    `crac_status` TINYINT NULL DEFAULT 0,
    `payment_status` TINYINT NULL DEFAULT 0,
    `payment_invoice` VARCHAR(45) NULL,
    `payment_method` VARCHAR(45) NULL,
    `transaction_id` VARCHAR(45) NULL,
    `created_at` DATETIME NULL DEFAULT NOW(),
    `is_cancelled` TINYINT NULL DEFAULT 0,
    `cancellation_remark` VARCHAR(255) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
);

CREATE TABLE `neepco_procure_sih`.`org_emp` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NULL,
    `designation` VARCHAR(45) NULL,
    `email_id` VARCHAR(255) NULL,
    `phone_no` VARCHAR(45) NULL,
    `password` VARCHAR(255) NULL,
    `org_id` INT NULL,
    `GSTIN` VARCHAR(45) NULL,
    `buyer_ryts` TINYINT NULL DEFAULT 0,
    `consignee_ryts` TINYINT NULL DEFAULT 0,
    `pao_ryts` TINYINT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
);


CREATE TABLE `neepco_procure_sih`.`budget_creation` (
    `id` INT NOT NULL,
    `org_id` INT NULL,
    `category` VARCHAR(45) NULL,
    `total_budget` BIGINT NULL DEFAULT 0,
    `mse_avail_budget` BIGINT NULL DEFAULT 0,
    `mse_scst_avail_budget` BIGINT NULL DEFAULT 0,
    `not_mse_avail_budget` BIGINT NULL DEFAULT 0,
    `year` YEAR NULL DEFAULT 0,
    PRIMARY KEY (`id`)
);

CREATE TABLE `neepco_procure_sih`.`procurement_annual_plan_files` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `org_id` INT NULL,
    `filepath` VARCHAR(255) NULL,
    `year` YEAR NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
);

ALTER TABLE `neepco_procure_sih`.`budget_creation` 
ADD COLUMN `gross_amt` TINYINT NULL AFTER `year`,
ADD COLUMN `net_amt` TINYINT NULL AFTER `gross_amt`,
ADD COLUMN `startDate` DATE NULL AFTER `net_amt`,
ADD COLUMN `endDate` DATE NULL AFTER `startDate`;


ALTER TABLE `neepco_procure_sih`.`procurement_details` 
ADD COLUMN `status` INT NULL AFTER `cancellation_remark`,
ADD COLUMN `is_gem` TINYINT NULL AFTER `status`,
ADD COLUMN `is_central` TINYINT NULL AFTER `is_gem`,
ADD COLUMN `invoice_doc` VARCHAR(255) NULL AFTER `is_central`,
ADD COLUMN `prc_doc` VARCHAR(255) NULL AFTER `invoice_doc`,
ADD COLUMN `crac` VARCHAR(255) NULL AFTER `prc_doc`;
ADD COLUMN `gem_central_id` VARCHAR(45) NULL AFTER `crac`;
ADD COLUMN `start_date` DATE NULL AFTER `gem_central_id`,
ADD COLUMN `end_date` DATE NULL AFTER `start_date`,
ADD COLUMN `allocated_budget` BIGINT NULL AFTER `end_date`;



ALTER TABLE `neepco_procure_sih`.`procurement_details` 
DROP COLUMN `is_central`,
DROP COLUMN `status`,
ADD COLUMN `type` VARCHAR(45) NULL AFTER `product`,
ADD COLUMN `category` VARCHAR(100) NULL AFTER `type`,
CHANGE COLUMN `prc_doc` `prc_file_path` VARCHAR(255) NULL DEFAULT NULL AFTER `prc_status`,
CHANGE COLUMN `crac` `crac_file_path` VARCHAR(255) NULL DEFAULT NULL AFTER `crac_status`,
CHANGE COLUMN `gem_central_id` `portal_id` VARCHAR(45) NULL DEFAULT NULL AFTER `portal`,
CHANGE COLUMN `is_gem` `portal` TINYINT NULL DEFAULT NULL ;


ALTER TABLE `procurement_details` 
DROP COLUMN `is_central`,
DROP COLUMN `status`,
ADD COLUMN `type` VARCHAR(45) NULL AFTER `product`,
ADD COLUMN `category` VARCHAR(100) NULL AFTER `type`,
CHANGE COLUMN `prc_doc` `prc_file_path` VARCHAR(255) NULL DEFAULT NULL AFTER `prc_status`,
CHANGE COLUMN `crac` `crac_file_path` VARCHAR(255) NULL DEFAULT NULL AFTER `crac_status`,
CHANGE COLUMN `gem_central_id` `portal_id` VARCHAR(45) NULL DEFAULT NULL AFTER `portal`,
CHANGE COLUMN `is_gem` `portal` TINYINT NULL DEFAULT NULL ;


ALTER TABLE `procurement_details` 
DROP COLUMN `gem_id`;


ALTER TABLE `budget_creation` 
CHANGE COLUMN `id` `id` INT NOT NULL AUTO_INCREMENT ,
ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE;
;

ALTER TABLE `budget_creation` 
ADD COLUMN `women_scst_budget` BIGINT NULL AFTER `mse_scst_avail_budget`;

ALTER TABLE `budget_creation` 
CHANGE COLUMN `women_scst_budget` `women_scst_budget` BIGINT NULL DEFAULT 0 ;


CREATE TABLE `categories` (
    `id` INT NOT NULL,
    `categoryName` VARCHAR(127) NULL,
    `type` TINYINT NULL,
    PRIMARY KEY (`id`)
);

ALTER TABLE `categories` 
CHANGE COLUMN `id` `id` INT NOT NULL AUTO_INCREMENT ,
ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE;
;

ALTER TABLE `categories` 
CHANGE COLUMN `categoryName` `categoryName` VARCHAR(255) NULL DEFAULT NULL ;


CREATE TABLE `budget_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc_name` VARCHAR(255) NULL,
  `category` VARCHAR(255) NULL,
  `is_small_scale` TINYINT NULL,
  `source` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `quantity_unit` VARCHAR(45) NULL,
  `budget_total` BIGINT NULL,
  `budget_other_mse` BIGINT NULL,
  `budget_mse_scst_inc_entrep` BIGINT NULL,
  `budget_mse_scst_own_entrep` BIGINT NULL,
  `budget_mse_scst_women` BIGINT NULL,
  `year` YEAR NULL,
  `gross_amt` TINYINT NULL,
  `net_amt` TINYINT NULL,
  `startDate` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


ALTER TABLE `budget_table` 
ADD COLUMN `org_id` INT NULL AFTER `id`;





function insertInTable(){
    const q="INSERT INTO categories (categoryName, type) VALUES (?, 0)";
    const cats=[
        "AAC/& ACSR Conductor upto 19 strands",
        "Agricultural Implements",
        "Hand Operated tools & implements",
        "Animal driven implements",
        "Air/Room Coolers",
        "Aluminium builder's hardware",
        "Ambulance stretcher",
        "Ammeters/ohm meter/Volt meter (Electro magnetic upto Class I accuracy)",
        "Anklets Web Khaki",
        "Augur (Carpenters)",
        "Automobile Head lights Assembly",
        "Badges cloth embroidered and metals",
        "Bags of all types i.e. made of leather, cotton, canvas & jute etc. including kit bags, mail bags, sleeping bags & water-proof bag",
        "Bandage cloth",
        "Barbed Wire",
        "Basket cane ",
        "Bath tubs",
        "Battery Charger",
        "Battery Eliminator",
        "Beam Scales (upto 1.5 tons)",
        "Belt leather & straps",
        "Bench Vices",
        "Bituminous Paints",
        "Blotting Paper",
        "Bolts & Nuts",
        "Bolts Sliding",
        "Bone Meal",
        "Boot Polish",
        "Boots & Shoes of all types including canvas shoes",
        "Bowls",
        "Boxes Leather",
        "Boxes made of metal",
        "Braces",
        "Brackets other than those used in Railways",
        "Brass Wire",
        "Brief Cases (other than moulded luggage)",
        "Brooms",
        "Brushes of all types",
        "Buckets of all types",
        "Button of all types",
        "Candle Wax Carriage",
        "Cane Valves/stock valves (for water fittings only)",
        "Cans metallic (for milk & measuring)",
        "Canvas Products ",
        "Water Proof Deliver, Bags to spec. No. IS - 1422/70",
        "Bonnet Covers & Radiators Muff. to spec. Drg. Lv 7/NSN/IA/130295",
        "Capes Cotton & Woollen",
        "Capes Waterproof",
        "Castor Oil",
        "Ceiling roses upto 15 amps",
        "Centrifugal steel plate blowers",
        "Centrifugal Pumps suction & delivery 150 mm. x 150 mm",
        "Chaff Cutter Blade",
        "Chains lashing",
        "Chappals and sandals",
        "Chamois Leather",
        "Chokes for light fitting",
        "Chrome Tanned leather (Semi-finished Buffalo & Cow)",
        "Circlips",
        "Claw Bars and Wires",
        "Cleaning Powder",
        "Clinical Thermometers",
        "Cloth Covers",
        "Cloth Jaconet",
        "Cloth Sponge",
        "Coir fibre and Coir yarn",
        "Coir mattress cushions and matting",
        "Coir Rope hawserlaid",
        "Community Radio Receivers",
        "Conduit pipes",
        "Copper nail",
        "Copper Napthenate",
        "Copper sulphate",
        "Cord Twine Maker",
        "Cordage Others",
        "Corrugated Paper Board & Boxes",
        "Cotton Absorbent",
        "Cotton Belts",
        "Cotton Carriers",
        "Cotton Cases",
        "Cotton Cord Twine",
        "Cotton Hosiery",
        "Cotton Packs",
        "Cotton Pouches",
        "Cotton Ropes",
        "Cotton Singlets",
        "Cotton Sling",
        "Cotton Straps",
        "Cotton tapes and laces",
        "Cotton Wool (Non absorbent)",
        "Crates Wooden & plastic",
        "Crucibles upto No. 200",
        "Crucibles Graphite upto No. 500",
        "Other Crucibles upto 30 kgs.",
        "Cumblies & blankets",
        "Curtains mosquito",
        "Cutters",
        "Dibutyl phthalate",
        "Diesel engines upto 15 H.P",
        "Dimethyl Phthalate",
        "Disinfectant Fluids",
        "Distribution Board upto 15 amps",
        "Domestic Electric appliances as per BIS Specifications",
        "Toaster Electric, Elect. Iron, Hot Plates, Elect. Mixer, Grinders Room heaters & convectors and ovens",
        "Domestic (House Wiring) P.V.C. Cables and Wires (Aluminium) Conforming to the prescribed BIS Specifications and upto 10.00 mm sq. nominal cross section",
        "Drawing & Mathematical Instruments",
        "Drums & Barrels",
        "Dust Bins",
        "Dust Shield leather",
        "Dusters Cotton all types except the items required in Khadi",
        "Azo Dyes (Direct & Acid)",
        "Basic Dyes",
        "Electric Call bells/buzzers/door bells",
        "Electric Soldering Iron",
        "Electric Transmission Line Hardware items like steel cross bars, cross arms clamps arching horn, brackets, etc",
        "Electronic door bell",
        "Emergency Light (Rechargeable type)",
        "Enamel Wares & Enamel Utensils",
        "Equipment camouflage Bamboo support",
        "Exhaust Muffler",
        "Expanded Metal",
        "Eyelets",
        "Film Polythene - including wide width film",
        "Film spools & cans",
        "Fire Extinguishers (wall type)",
        "Foot Powder",
        "French polish",
        "Funnels",
        "Fuse Cut outs",
        "Fuse Unit",
        "Garments (excluding supply from Indian Ordnance Factories)",
        "Gas mantels",
        "Gauze cloth",
        "Gauze surgical all types",
        "Ghamellas (Tasllas)",
        "Glass Ampules",
        "Glass & Pressed Wares",
        "Glue",
        "Grease Nipples & Grease guns",
        "Gun cases",
        "Gun Metal Bushes",
        "Gumtape",
        "Hand drawn carts of all types",
        "Hand gloves of all types",
        "Hand Lamps Railways",
        "Hand numbering machine",
        "Hand pounded Rice (polished and unpolished)",
        "Hand presses",
        "Hand Pump",
        "Hand Tools of all types",
        "Handles wooden and bamboo (Procurement can also be made from State Forest Corpn. and State Handicrafts Corporation)",
        "Harness Leather",
        "Hasps & Staples",
        "Haver Sacks",
        "Helmet Non-Metallic",
        "Hide and country leather of all types",
        "Hinges",
        "Hob nails",
        "Holdall",
        "Honey",
        "Horse and Mule Shoes",
        "Hydraulic Jacks below 30 ton capacity",
        "Insecticides Dust and Sprayers (Manual only)",
        "Invalid wheeled chairs.",
        "Invertor domestic type upto 5 kvA",
        "Iron (dhobi)",
        "Key board wooden",
        "Kit Boxes",
        "Kodali",
        "Lace leather",
        "Lamp holders",
        "Lamp signal",
        "Lanterns Posts & bodies",
        "Lanyard",
        "Latex foam sponge",
        "Lathies",
        "Letter Boxes",
        "Lighting Arresters - upto 22 kv",
        "Link Clip",
        "Linseed Oil",
        "Lint Plain",
        "Lockers",
        "Lubricators",
        "L.T. Porcelain KITKAT & Fuse Grips",
        "Machine Screws",
        "Magnesium Sulphate",
        "Mallet Wooden",
        "Manhole covers",
        "Measuring Tapes and Sticks",
        "Metal clad switches (upto 30 Amps)",
        "Metal Polish",
        "Metallic containers and drums other than N.E.C. (Not elsewhere classified)",
        "Metric weights",
        "Microscope for normal medical use",
        "Miniature bulbs (for torches only)",
        "M.S. Tie Bars",
        "Nail Cutters",
        "Naphthalene Balls",
        "Newar",
        "Nickel Sulphate",
        "Nylon Stocking",
        "Nylon Tapes and Laces",
        "Oil Bound Distemper",
        "Oil Stoves (Wick stoves only)",
        "Pad locks of all types",
        "Paint remover",
        "Palma Rosa Oil",
        "Palmgur",
        "Pans Lavatory Flush",
        "Paper conversion products, paper bags, envelops, Ice-cream cup, paper cup and saucers & paper  Plates",
        "Paper Tapes (Gummed)",
        "Pappads",
        "Pickles & Chutney",
        "Piles fabric",
        "Pillows",
        "Plaster of Paris",
        "Plastic Blow Moulded Containers upto 20 litre excluding Poly Ethylene Terephthalate (PET) Containers",
        "Plastic cane",
        "Playing Cards",
        "Plugs & Sockets electric upto 15 Amp",
        "Polythene bags",
        "Polythene Pipes",
        "Post Picket (Wooden)",
        "Postal Lead seals",
        "Potassium Nitrate",
        "Pouches",
        "Pressure Die Casting upto 0.75 kg",
        "Privy Pans",
        "Pulley Wire",
        "PVC footwears",
        "PVC pipes upto 110 mm",
        "PVC Insulated Aluminium Cables (upto 120 sq. mm) (ISS:694)",
        "Quilts, Razais",
        "Rags",
        "Railway Carriage light fittings",
        "Rakes Ballast",
        "Razors",
        "RCC Pipes upto 1200 mm. dia",
        "RCC Poles Prestressed",
        "Rivets of all types",
        "Rolling Shutters",
        "Roof light Fittings",
        "Rubber Balloons",
        "Rubber Cord",
        "Rubber Hoses (Unbranded)",
        "Rubber Tubing (Excluding braided tubing)",
        "Rubberised Garments Cap and Caps etc.",
        "Rust/Scale Removing composition",
        "Safe meat & milk",
        "Safety matches",
        "Safety Pins (and other similar products like paper pins, staples pins etc.)",
        "Sanitary Plumbing fittings",
        "Sanitary Towels",
        "Scientific Laboratory glasswares (Barring sophisticated items)",
        "Scissors cutting (ordinary)",
        "Screws of all types including High Tensile",
        "Sheep skin all types",
        "Shellac",
        "Shoe laces",
        "Shovels",
        "Sign Boards painted",
        "Silk ribbon",
        "Silk Webbing",
        "Skiboots & shoes",
        "Sluice Valves",
        "Snapfastner (Excluding 4 pcs. ones)",
        "Soap Carbolic",
        "Soap Curd",
        "Soap Liquid",
        "Soap Soft",
        "Soap washing or laundary soap",
        "Soap Yellow",
        "Socket/pipes",
        "Sodium Nitrate",
        "Sodium Silicate",
        "Sole leather",
        "Spectacle frames",
        "Spiked boot",
        "Sports shoes made out of leather (for all Sports games)",
        "Squirrel Cage Induction Motors upto and including 100 KW440 volts 3 phase",
        "Stapling machine",
        "Steel Almirah",
        "Steel beds stead",
        "Steel Chair",
        "Steel desks",
        "Steel racks/shelf",
        "Steel stools",
        "Steel trunks",
        "Steel wool",
        "Steel & aluminium windows and ventilators",
        "Stockinet",
        "Stone and stone quarry rollers",
        "Stoneware jars",
        "Stranded Wire",
        "Street light fittings",
        "Student Microscope",
        "Studs (excluding high tensile)",
        "Surgical Gloves (Except Plastic)",
        "Table knives (Excluding Cutlery)",
        "Tack Metallic",
        "Taps",
        "Tarpaulins",
        "Teak fabricated round blocks",
        "Tent Poles",
        "Tentage Civil/Military & Salitah Jute for Tentage",
        "Textiles manufacturers other than N.E.C. (not elsewhere classified)",
        "Tiles",
        "Tin Boxes for postage stamp",
        "Tin can unprinted upto 4 gallons capacity (other than can O.T.S.)",
        "Tin Mess",
        "Tip Boots",
        "Toggle Switches",
        "Toilet Rolls",
        "Transformer type welding sets conforming to IS:1291/75 (upto 600 amps)",
        "Transistor Radio upto 3 band",
        "Transistorised Insulation - Testers",
        "Trays",
        "Trays for postal use",
        "Trolley",
        "Trollies - drinking water",
        "Tubular Poles",
        "Tyres & Tubes (Cycles)",
        "Umbrellas",
        "Utensils all types",
        "Valves Metallic",
        "Varnish Black Japan",
        "Voltage Stablisers including C.V.T's",
        "Washers all types",
        "Water Proof Covers",
        "Water Proof paper",
        "Water tanks upto 15,000 litres capacity",
        "Wax sealing",
        "Waxed paper",
        "Weighing Scale",
        "Welded Wiremash",
        "Wheel barrows",
        "Whistle",
        "Wicks cotton",
        "Wing Shield Wipers (Arms & Blades only)",
        "Wire brushes and Fibre Brushes",
        "Wire Fencing & Fittings",
        "Wire nails and Horse shoe nails",
        "Wire nettings of gauze thicker than 100 mesh size",
        "Wood Wool",
        "Wooden ammunition boxes",
        "Wooden Boards",
        "Wooden Box for Stamps",
        "Wooden Boxes and Cases N.E.C. (Not elsewhere classified)",
        "Wooden Chairs",
        "Wooden Flush Door Shutters",
        "Wooden packing cases all sizes",
        "Wooden pins",
        "Wooden plugs",
        "Wooden shelves",
        "Wooden veneers",
        "Woollen hosiery",
        "Zinc Sulphate",
        "Zip Fasteners"
    ];
    cats.forEach((cate) =>{
        if(cate.length > 127) db.query(q,[cate],(err,data) => {
            if (err){
                console.log(err);
                console.log(cate.length);
            }
            
        });
    });


}